export const ACTION_TYPE = {
    SET_USER: 'SET_USER',
    LOGOUT: 'LOGOUT',
    SET_POST_DATA: 'SET_POST_DATA',
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    RESET_POST_DATA: 'RESET_POST_DATA',
    ADD_COMMENT: 'ADD_COMMENT',
    REMOVE_COMMENT: 'REMOVE_COMMENT',

    OPEN_EDIT_CATEGORY_MODAL: 'OPEN_EDIT_CATEGORY_MODAL',
    OPEN_CREATE_CATEGORY_MODAL: 'OPEN_CREATE_CATEGORY_MODAL',
    CLOSE_CATEGORY_MODAL: 'CLOSE_CATEGORY_MODAL',
    SET_CATEGORY_DATA: 'SET_CATEGORY_DATA',
    RESET_CATEGORY_DATA: 'RESET_CATEGORY_DATA',

    OPEN_EDIT_ACCOUNT_MODAL: 'OPEN_EDIT_ACCOUNT_MODAL',
    OPEN_CREATE_ACCOUNT_MODAL: 'OPEN_CREATE_ACCOUNT_MODAL',
    CLOSE_ACCOUNT_MODAL: 'CLOSE_ACCOUNT_MODAL',
    SET_ACCOUNT_DATA: 'SET_ACCOUNT_DATA',
    RESET_ACCOUNT_DATA: 'RESET_ACCOUNT_DATA',

    OPEN_EDIT_ACCOUNT_TYPE_MODAL: 'OPEN_EDIT_ACCOUNT_TYPE_MODAL',
    OPEN_CREATE_ACCOUNT_TYPE_MODAL: 'OPEN_CREATE_ACCOUNT_TYPE_MODAL',
    CLOSE_ACCOUNT_TYPE_MODAL: 'CLOSE_ACCOUNT_TYPE_MODAL',
    SET_ACCOUNT_TYPE_DATA: 'SET_ACCOUNT_TYPE_DATA',
    RESET_ACCOUNT_TYPE_DATA: 'RESET_ACCOUNT_TYPE_DATA',


    OPEN_EDIT_TRANSACTION_MODAL: 'OPEN_EDIT_TRANSACTION_MODAL',
    OPEN_CREATE_TRANSACTION_MODAL: 'OPEN_CREATE_TRANSACTION_MODAL',
    CLOSE_TRANSACTION_MODAL: 'CLOSE_TRANSACTION_MODAL',
    SET_TRANSACTION_DATA: 'SET_TRANSACTION_DATA',
    RESET_TRANSACTION_DATA: 'RESET_TRANSACTION_DATA',
}

